#!/bin/bash
# AICM Machine Switch-In Protocol
# Run this AFTER arriving at a machine to sync and prepare environment.
# Per DISC-029: Cross-Platform Development Workflow Strategy.

set -e

echo "🔄 AICM Machine Switch-In Protocol"
echo "==================================="
echo ""

# Get script directory and repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# 1. Fetch and pull latest
echo "⬇️  Pulling latest changes..."
git fetch origin
BRANCH=$(git branch --show-current)
git pull origin "$BRANCH"

# 2. Show recent changes
echo ""
echo "📋 Recent commits:"
git log --oneline -5
echo ""

# 3. Show what files changed
echo "📁 Files changed in last commit:"
git diff --name-only HEAD~1 2>/dev/null || echo "(first commit or no history)"
echo ""

# 4. Detect environment
echo "🖥️  Environment Detection:"
echo "--------------------------"
python scripts/detect_env.py 2>/dev/null || echo "⚠️  detect_env.py not found"
echo ""

# 5. Platform-specific guidance
if [[ "$(uname)" == "Darwin" ]]; then
    echo "🍎 Mac Native Mode Detected"
    echo "═══════════════════════════"
    echo ""
    echo "Quick Start Commands:"
    echo "  make dev          # Start dev server"
    echo "  make test         # Run tests"
    echo "  pytest tests/ -v  # Run tests directly"
    echo ""
    echo "Manual Start:"
    echo "  python -m uvicorn backend.main:app --reload --port 8100"
    echo ""
else
    echo "🪟 Windows/WSL Docker Mode Detected"
    echo "════════════════════════════════════"
    echo ""
    echo "Quick Start Commands:"
    echo "  make docker-up    # Start containers"
    echo "  make test         # Run tests in container"
    echo ""
    echo "Manual Start:"
    echo "  docker compose --profile main up -d"
    echo ""
    echo "View Logs:"
    echo "  docker logs -f aidev-backend"
    echo ""
fi

# 6. Update machine state file
echo "📝 Updating machine state..."
SESSION_FILE=".sessions/CURRENT_MACHINE.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD)

cat > "$SESSION_FILE" << EOF
# Current Machine State

> **Auto-generated by switch_in.sh**

**Last Active**: $TIMESTAMP
**Machine**: $(hostname)
**Branch**: $BRANCH
**Commit**: $COMMIT
**Status**: Active development

## Environment

$(python scripts/detect_env.py 2>/dev/null || echo "Run: python scripts/detect_env.py")

## Before Leaving This Machine

\`\`\`bash
./scripts/switch_out.sh
\`\`\`
EOF

echo ""
echo "════════════════════════════════════════════════════"
echo "✅ Ready to work on $(hostname)!"
echo ""
echo "Before leaving, run: ./scripts/switch_out.sh"
echo "════════════════════════════════════════════════════"
