# AICM Machine Switch-Out Protocol (Windows PowerShell)
# Run this BEFORE leaving a machine to ensure all work is synced.
# Per DISC-029: Cross-Platform Development Workflow Strategy.

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "🔄 AICM Machine Switch-Out Protocol" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Get repo root
$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

# 1. Check for uncommitted changes
Write-Host "📋 Checking git status..." -ForegroundColor Yellow
$status = git status --porcelain
if ($status) {
    Write-Host ""
    Write-Host "📝 Uncommitted changes detected:" -ForegroundColor Yellow
    git status --short
    Write-Host ""

    $commit = Read-Host "Commit all changes? [Y/n]"
    if ($commit -ne 'n' -and $commit -ne 'N') {
        git add -A
        Write-Host ""
        $msg = Read-Host "Commit message (or press Enter for WIP)"
        if (-not $msg) { $msg = "WIP: switching machines" }
        git commit -m $msg
    } else {
        Write-Host "❌ Aborting - commit your changes first" -ForegroundColor Red
        exit 1
    }
} else {
    Write-Host "✅ Working directory clean" -ForegroundColor Green
}

# 2. Push to remote
Write-Host ""
Write-Host "⬆️  Pushing to origin..." -ForegroundColor Green
$branch = git branch --show-current
git push origin $branch

# 3. Run tests (optional)
Write-Host ""
$runTests = Read-Host "Run tests before switch? [y/N]"
if ($runTests -eq 'y' -or $runTests -eq 'Y') {
    Write-Host "🧪 Running tests..." -ForegroundColor Yellow
    $dockerRunning = docker ps 2>$null | Select-String "aidev-backend"
    if ($dockerRunning) {
        docker exec aidev-backend pytest tests/ -v --tb=short -q
    } else {
        Write-Host "⚠️  Docker not running, running natively..." -ForegroundColor Yellow
        python -m pytest tests/ -v --tb=short -q
    }
}

# 4. Update machine state file
Write-Host ""
Write-Host "📝 Updating machine state..." -ForegroundColor Yellow
$sessionFile = ".sessions/CURRENT_MACHINE.md"
$timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
$commitHash = git rev-parse --short HEAD
$lastMsg = git log -1 --pretty=format:"%s"

$content = @"
# Current Machine State

> **Auto-generated by switch_out.ps1**

**Last Active**: $timestamp
**Machine**: $env:COMPUTERNAME
**Branch**: $branch
**Commit**: $commitHash
**Status**: Switched out - ready for other machine

## Last Commit

$lastMsg

## To Continue on Other Machine

```bash
git pull && ./scripts/switch_in.sh
```

## Environment

Windows 11 / Docker Desktop / WSL2
GPU: NVIDIA RTX 5090 (32GB) + RTX 3090 Ti (24GB)
"@

Set-Content -Path $sessionFile -Value $content

git add $sessionFile
git commit -m "chore: machine switch-out from $env:COMPUTERNAME" --no-verify
git push origin $branch

Write-Host ""
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Green
Write-Host "✅ Ready to switch!" -ForegroundColor Green
Write-Host ""
Write-Host "On the other machine, run:" -ForegroundColor White
Write-Host "   git pull && ./scripts/switch_in.sh" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════" -ForegroundColor Green
