#!/bin/bash
# AICM Machine Switch-Out Protocol
# Run this BEFORE leaving a machine to ensure all work is synced.
# Per DISC-029: Cross-Platform Development Workflow Strategy.

set -e

echo "🔄 AICM Machine Switch-Out Protocol"
echo "===================================="
echo ""

# Get script directory and repo root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# 1. Check for uncommitted changes
echo "📋 Checking git status..."
if [[ -n $(git status --porcelain) ]]; then
    echo ""
    echo "📝 Uncommitted changes detected:"
    git status --short
    echo ""

    read -p "Commit all changes? [Y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
        git add -A
        echo ""
        read -p "Commit message (or press Enter for WIP): " msg
        git commit -m "${msg:-WIP: switching machines}"
    else
        echo "❌ Aborting - commit your changes first"
        exit 1
    fi
else
    echo "✅ Working directory clean"
fi

# 2. Push to remote
echo ""
echo "⬆️  Pushing to origin..."
BRANCH=$(git branch --show-current)
git push origin "$BRANCH"

# 3. Run tests (optional)
echo ""
read -p "Run tests before switch? [y/N] " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "🧪 Running tests..."
    if [[ "$(uname)" == "Darwin" ]]; then
        python -m pytest tests/ -v --tb=short -q || echo "⚠️  Some tests failed"
    else
        if docker ps | grep -q aidev-backend; then
            docker exec aidev-backend pytest tests/ -v --tb=short -q || echo "⚠️  Some tests failed"
        else
            echo "⚠️  Docker not running, running natively..."
            python -m pytest tests/ -v --tb=short -q || echo "⚠️  Some tests failed"
        fi
    fi
fi

# 4. Update machine state file
echo ""
echo "📝 Updating machine state..."
SESSION_FILE=".sessions/CURRENT_MACHINE.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT=$(git rev-parse --short HEAD)
LAST_MSG=$(git log -1 --pretty=format:"%s")

cat > "$SESSION_FILE" << EOF
# Current Machine State

> **Auto-generated by switch_out.sh**

**Last Active**: $TIMESTAMP
**Machine**: $(hostname)
**Branch**: $BRANCH
**Commit**: $COMMIT
**Status**: Switched out - ready for other machine

## Last Commit

$LAST_MSG

## To Continue on Other Machine

\`\`\`bash
git pull && ./scripts/switch_in.sh
\`\`\`

## Environment

$(python scripts/detect_env.py 2>/dev/null || echo "Run: python scripts/detect_env.py")
EOF

git add "$SESSION_FILE"
git commit -m "chore: machine switch-out from $(hostname)" --no-verify
git push origin "$BRANCH"

echo ""
echo "════════════════════════════════════════════════════"
echo "✅ Ready to switch!"
echo ""
echo "On the other machine, run:"
echo "   git pull && ./scripts/switch_in.sh"
echo "════════════════════════════════════════════════════"
